users:
  - name: FIN
    login: FIN
    email: foo@foo.com
  - name: ATT
    login: ATT
    email: foo@foo.com
  - name: STS
    login: STS
    email: foo@foo.com
    permit_repos:
      - slug: FIN/test-repo
        permissions:
          admin: false
          push: false
          pull: false
      - slug: ATT/att-ng
        permissions:
          admin: true
          push: true
          pull: true

#
repos:
  - name: test-repo
    url: https://stash.yourcompany.com/projects/FIN/repos/test-repo/browse
    active: true
    private: false
    provider: stash
    owner_name: FIN
  - name: atom-ng
    url: https://stash.yourcompany.com/projects/ATT/repos/att-ng/browse
    active: true
    private: false
    provider: stash
    owner_name: ATT
  - name: build-scripts
  url: https://stash.yourcompany.com/projects/STS/repos/test-repo/browse
    active: true
    private: false
    provider: stash
    owner_name: STS

